### ISSUE TITLE
No arranca correctamente

### ISSUE THREAD

**Issue by CarlesLlobet** [pablopb3/biwenger-api#1]
Buenas,

Me interesa usar la api de biwenger para crear una tool, pero dado que no hay ninguna documentación oficial, queria usar tu proyecto para ver como funcionaba y luego hacer la mia en python en base a lo tuyo.

El punto es que al levantar los containers el de mongo no funcionaba correctamente. Mirando los logs vi que era un problema con el shared volume (tipico con docker en windows), por lo que deje solo declarado el volumen sin hacer un shared al host.

Los dos containers se levantan correctamente pero no consigo que localhost:8080 me devuelva nada, ni desde el navegador ni con curls como el de login.

**Comment by CarlesLlobet** [comment]
Puede que sea porque no estan puestos mi userID i mi leagueID en el app.properties?
Como los consigues?

**Comment by CarlesLlobet** [comment]
> Puede que sea porque no estan puestos mi userID i mi leagueID en el app.properties?
> Como los consigues?

No era eso, los he sacado con el burp y el mobil y sigue dandome:
`curl: (7) Failed to connect to localhost port 8080: Connection refused`

**Comment by CarlesLlobet** [comment]
Reconstruyendo (--build) con mis datos, consigo que me responda, pero me responde un 404 page not found.

Entiendo que en el navegador pase, pero haciendo la peticion POST con curl me responde lo mismo :S

**Comment by pablopb3** [comment]
Buenas, que tal? Gracias por el interés!

Hice la API a correr para intentar llegar a principio de temporada y muchas cosas están cogidas con pinzas. Busqué como primer objetivo tener algo que funcionase para mí. 

Tenía en mente ir mejorando el código poco a poco y hacer que funcionase de manera general, y ahora que veo que hay gente interesada le daré más prioridad. Intentaré que se pueda arrancar en cualquier entorno lo antes posible y mejorar la documentación.

Así de primeras, no sé cual puede ser el problema en tu caso. Intentaré reproducirlo en windows y ver donde puede estar el problema. Actualizo con lo que descubra.

**Comment by pablopb3** [comment]
Para empezar, veo que si añades "/v1" a la url, la api te dará respuesta. Estaba mal la docu. Sorry. 

Aún así, creo que la configuración del arranque del mongo no es correcta. Necesita crear una db que se llame biwenger y una collection que se llame players. Voy a intentar modificar el docker-compose para que arranque el mongo con la configuración correcta.

**Comment by pablopb3** [comment]
This issue should be fixed with #2. Documentation has change a little bit. Please, try again and give me some feedback.

**Comment by CarlesLlobet** [comment]
Buenas Pablo!
Gracias por las respuestas. Efectivamente he provado lo del /v1 y por eso me daba page not found. Ahora me devuelve el saludo correctamente desde el navegador, aunque haciendo el curl a /v1/login me responde un Empty.. tendre que hacer mas pruebas jaja.
Te sugiero un par de cambios:

- Actualizar los ejemplos y el README para añadir el /v1.
- Actualizar el README i incluir el hecho de que el mongo se genere correctamente (no solo con la creación de las db que toque, sino tambien te sugiero cambiar el volumen compartido por un volumen normal, dado que puede dar errores en windows si tienes una partición, como me pasó a mi).
- Añadir en el README que antes de compilar por primera vez (`docker compose up -d --build`) se tienen que poner bien los IDs de usuario y liga. Tambien explicaría como se pueden sacar de manera facil. Yo lo hice con el burp interceptando las requests de mi mobil, pero seguro que hay una manera mas facil.

Un saludo, y gracias por tu respuesta!

**Comment by pablopb3** [comment]
El readme ya ha sido actualizado para que la integración resulte más fácil.

Muchas gracias por las sugerencias.
