### ISSUE TITLE
Shared volumes of Mongo not working in Windows

### ISSUE THREAD

**Issue by CarlesLlobet** [pablopb3/biwenger-api#3]
Buenas,
En Windows cuando intentas levantar los containers, el de mongo da problemas con el shared volume por temas de permisos con linux, como se ve a continuación:
![image](https://user-images.githubusercontent.com/6575422/65775249-18b23700-e140-11e9-9a43-bc8c47ed1c3d.png)

**Propuesta de solución**
Como no hay necesidad de que la base de datos este compartida con el host, i puede quedarse dentro del container, se propone el siguiente cambio:

- Cambiar en el docker compose del container de mongo esto: `- ./data/db:/data/db`  
- Por esto: `- /data/db` 

El volumen del script no da problemas con compartirlo por lo que la solución no afecta a la creación correcta de la base de datos. 
Y de hecho es mas comodo de consultar dado que no tienes que instalarte un cliente de mongo en el host, sino que puedes usar el del propio container para consultar la base de datos:
`docker exec -it biwenger-mongo mongo`

**Comment by pablopb3** [comment]
Arreglado en 86173fb.
