### ISSUE TITLE
API Functions not responding correctly

### ISSUE THREAD

**Issue by CarlesLlobet** [pablopb3/biwenger-api#4]
Buenas,

Una vez arrancados los containers i conseguido que me responda bien la API con el greeting, he empezado a probar las funciones.

- La función `login` parece funcionar correctamente y devolverme un token, pero después lo uso para llamar a `getMyPlayers` y no me responde correctamente, como se puede ver a continuación:
![image](https://user-images.githubusercontent.com/6575422/65776241-05a06680-e142-11e9-8595-cc12f7ef2d1a.png)

- La función `updatePlayersAlias` parece que funciona correctamente, pero cuando entro a la base de datos, me aparecen jugadores que no son mios (quizas son tuyos?). Lo he comprobado y en el application.properties estan mi userID i leagueID correctos, y he reconstruido el container despues de ponerlos i dentro del container tambien estan correctos, o sea que ha compilado con los correctors. 
A continuación te dejo evidencias de los que me guarda en la BD i los que tengo en la liga i usuario especificados:
![image](https://user-images.githubusercontent.com/6575422/65776441-72b3fc00-e142-11e9-8254-7832e5e08005.png)
![image](https://user-images.githubusercontent.com/6575422/65776445-75aeec80-e142-11e9-9493-2141741461b8.png)

He estado mirando el código pero no veo donde puede estar el error (tampoco se demasiado de go).
Creo que entre los dos podemos mejorar mucho la API i el Bot. Quiero implementar funciones de poder mirar las pujas de cada jugador i pujar en funcion de varios parametros. Si quieres, si me dejas una manera de contacto más agil (Telegram por ejemplo) podemos hablarlo por ahi.

Un saludo,

**Comment by pablopb3** [comment]
Buenas,

El funcionamiento del UpdatePlayersAlias es correcto. Lo que hace es descargarse los ids y los alias de todos los jugadores de 1a división y almacenarlos en el mongodb. 

La función getMyPlayers veo que no funciona bien. Tendremos que ver qué se nos puede estar escapando. Veo que el token que te devuelve el login, aunque parecido, no es el mismo que usas luego en el getMyPlayers. Podría ser eso.

Estoy seguro de que podemos mejorar la API y añadirle muchas funcionalidades.

Un saludo.

**Comment by CarlesLlobet** [comment]
Buenas,

Efectivamente, UpdatePlayersAlias funciona correctamente, error mio.

La función getMyPlayers sigue sin funcionarme. Debí hacerte una captura erronea, pero lo he probado muchas veces con el token correcto y no me devuelve nada. En esta captura puedes verlo con el token correcto:

![image](https://user-images.githubusercontent.com/6575422/65943037-d7b36e80-e42e-11e9-9fd2-2d5cf2939328.png)

En nada ya tenemos la API funcional para los dos y podre colaborar en muchas nuevas funciones ;)

Un saludo,

**Comment by CarlesLlobet** [comment]
Solved, the userID i got from the burp request was not correct.

Suggestions: 

- Specify in the readme that after changing your application.properties you should rebuild the container
- (For no-IT people) If they have Chrome, tell them to Click F12 to open the console, go to the Network tab, filter packets by XHR, reload the page, and click on the "home" request. There they'll find easy their IDs.
