### ISSUE TITLE
Simplemente una pregunta..

### ISSUE THREAD

**Issue by Ikav8** [pablopb3/biwenger-api#7]
Hola Pablo,

Estamos haciendo algo parecido y me ha resultado muy curioso ver que utilizas una api de bw.. Yo no he encontrado documentación al respecto la verdad.. 

Imagino que has estado peleándote con el navegador y viendo las URL a las que ataca.. ¿Tienes alguna lista de endpoints y su formato? ¿Te importaría compartir esta información?

Lo que estoy haciendo yo no es tanto gestionar el equipo como sacar datos para calcular saldos, pujas máximas, alguna estadística graciosa de los peores movimientos, etc.. 

Un saludo, 

Álex

**Comment by pablopb3** [comment]
Buenas!

No existe ninguna api de biwenger ni ningún tipo de documentación. Me creé yo esta api, que consigue replicar las peticiones que hace la app/web de biwenger a su backend.

De momento he creado las funcionalidades que me hicieron falta, pero la idea es ir mejorándola, así que si tenéis alguna sugerencia podéis crear un issue o incluso hacer alguna PR con métodos nuevos.

Un saludo,

Pablo.

**Comment by Ikav8** [comment]
Estupendo, muchas gracias!

No creo que haga PR porque estoy utilizando python pero conforme vaya terminando alguna cosilla te animo a que le eches un ojo por si quieres implementarla también ^^

Un saludo y suerte en la liga ^^
